### ISSUE TITLE
Consolidate assay specific processing

### ISSUE THREAD

**Issue by wshands** [hubmapconsortium/sc-atac-seq-pipeline#30]

**Comment by mruffalo** [comment]
Most assay-specific processing is in extraction of cellular barcodes, and the layout of the FASTQ files that are given as input.

For this functionality, assay-specific behavior should be triggered via the value of the `Assay` enum defined [here](https://github.com/hubmapconsortium/sc-atac-seq-pipeline/blob/develop/bin/utils.py#L58). When possible, things should use values attached to those enum constants, like [this](https://github.com/hubmapconsortium/salmon-rnaseq/blob/scvelo/bin/salmon/salmon_wrapper.py#L88), with conditional processing like [this](https://github.com/hubmapconsortium/salmon-rnaseq/blob/scvelo/bin/salmon/salmon_wrapper.py#L91) done as a last resort.

Assay-specific differences that come to mind:
- Number of FASTQ files: 3 for SNARE-seq and snATAC-seq, 2 for sciATAC-seq
- Barcoding scheme: how to extract barcodes from the input FASTQ files (which portions of which reads -- these are already in the read IDs for sciATAC-seq), and how to write the output

There should be one CWL step which accepts the FASTQ directory and assay and calls a Python script with those inputs, like [this script](https://github.com/hubmapconsortium/salmon-rnaseq/blob/scvelo/bin/analysis/adjust_barcodes.py) and [this CWL step](https://github.com/hubmapconsortium/salmon-rnaseq/blob/scvelo/steps/adjust-barcodes.cwl) in the Salmon scRNA-seq pipeline. That script dispatches to entirely different functions for different assays due to some huge differences in the scRNA-seq assays; things are much more uniform in scATAC-seq so that kind of approach may or may not be necessary.

All barcode extraction (and adding these to read barcodes) should be done in Python code run under PyPy3, with an image built from [this Dockerfile](https://github.com/hubmapconsortium/sc-atac-seq-pipeline/blob/develop/docker/barcode-adj/Dockerfile) that's already in the repository. The current barcode manipulation that's done in Perl should be trivial to implement in Python with code in the HuBMAP [`fastq-utils`](https://github.com/hubmapconsortium/fastq-utils) package, which is already included in the `barcode-adj` Docker image. Code like [this](https://github.com/hubmapconsortium/salmon-rnaseq/blob/scvelo/bin/analysis/correct_snareseq_barcodes.py) might be useful as inspiration; the barcode extraction in the scATAC-seq pipeline is much simpler than that (literally "extract barcode from the right location in the reads, add to read ID, write to new FASTQ file" -- no error correction or anything like that, just a direct redo of the Perl script).
